### ISSUE TITLE
colour map wrong order

### ISSUE THREAD

**Issue by hustlxx** [ysamano/TidyTuesday#2]
Hi,thanks for your great figure!

I think in your p1.
scale_fill_manual(values = rankings2$colour) is of the wrong order. because the dat.gg and labels_cir were arranged by year, but not rankings2.

So I modified this as: scale_fill_manual(values = rankings2 %>% 
                      arrange(year) %>% pull(colour))

**Comment by ysamano** [comment]
Thank you. I already corrected the graph
